---
version: "2.0"

services:
  ubuntu:
    image: ubuntu:22.04
    command:
      - "sh"
      - "-c"
    args:
      - sleep infinity 
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    ubuntu:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        ubuntu: 
          denom: uakt
          amount: 10000

deployment:
  ubuntu:
    akash:
      profile: ubuntu
      count: 1
